Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,3 +1,4 @@
+
 name: student-management ci-cd
 
 on:
@@ -10,11 +11,12 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+
       - name: Checkout code
-        uses: actions/checkout@v7
+        uses: actions/checkout@v4
 
       - name: Setup Java
-        uses: actions/setup-java@v6
+        uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: "21"
@@ -24,14 +26,17 @@ jobs:
         run: mvn clean package
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v6
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
 
       - name: Push Artifacts to S3
-        run: aws s3 cp target/*.war s3://krushna.online123123/Artifacts/student.war
+        run: |
+          aws s3 cp target/*.war \
+            s3://krushna.online123123/Artifacts/student.war
+
       - name: SonarQube Analysis
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -41,14 +46,25 @@ jobs:
             -Dsonar.token="$SONAR_TOKEN" \
             -Dsonar.host.url="$SONAR_HOST_URL"
 
-      - name: SonarQube Quality Gates
+      - name: SonarQube Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: |
-          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
-            "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=com.school:student-management" \
+          echo "Waiting for SonarQube Quality Gate..."
+
+          sleep 10
+
+          STATUS=$(curl -s -u "${SONAR_TOKEN}:" \
+            "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=com.school:student-management" \
             | jq -r '.projectStatus.status')
+
           echo "Quality Gate: $STATUS"
-          [ "$STATUS" = "OK" ] || exit 1
 
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed."
+            exit 1
+          fi
 
-
-        
+          echo "Quality Gate passed."
+```
